# Generated by Django 3.0.5 on 2020-04-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/products')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('desc', models.TextField()),
                ('brand', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.services')),
            ],
        ),
    ]
