# Generated by Django 3.0.5 on 2020-04-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_product_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productImage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productimage',
            new_name='productimage1',
        ),
        migrations.AddField(
            model_name='product',
            name='productimage2',
            field=models.ImageField(null=True, upload_to='static/img/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='productimage3',
            field=models.ImageField(null=True, upload_to='static/img/products'),
        ),
        migrations.AddField(
            model_name='services',
            name='servicedetail',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
